<?php

require_once "DomainObject.php";
class Document extends DomainObject
{
    public static function getGroup()
    {
        //return parent::getGroup(); // TODO: Change the autogenerated stub
        return "document";
    }
}